### ISSUE TITLE
Update to creative-central 1.1.0

### ISSUE THREAD

**Issue by yusshu** [unnamed/creative-faces#1]
Using creative-faces (latest version) and creative-central 1.1.0 causes an error:
```cs
[04:54:31 ERROR]: [creative-central] Error while generating resource pack
java.util.concurrent.CompletionException: java.lang.IncompatibleClassChangeError: Found interface team.unnamed.creative.ResourcePack, but class was expected
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-391]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.4.jar:git-Paper-391]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.IncompatibleClassChangeError: Found interface team.unnamed.creative.ResourcePack, but class was expected
        at team.unnamed.creativefaces.listener.ResourcePackGenerateListener.on(ResourcePackGenerateListener.java:32) ~[creative-faces-2.0.0.jar:?]
        at team.unnamed.creativefaces.listener.ResourcePackGenerateListener.on(ResourcePackGenerateListener.java:17) ~[creative-faces-2.0.0.jar:?]
        at team.unnamed.creative.central.common.event.EventBusImpl.call(EventBusImpl.java:83) ~[creative-central-bukkit-1.1.0-all.jar:?]
        at team.unnamed.creative.central.bukkit.CreativeCentralPlugin.generateSync(CreativeCentralPlugin.java:311) ~[creative-central-bukkit-1.1.0-all.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 6 more
```

Should be fixed by updating creative-central.

**Comment by yusshu** [comment]
Done! creative-faces `2.0.1` now uses creative-central `1.1.0`
